import { join } from 'node:path';
import type { MumuSpecConfig } from '../core/config.js';
import type { SpecContext } from '../core/types.js';
import { writeText } from '../core/utils.js';
import { PONYTAIL_LADDER, NON_LAZY_DOMAINS } from '../spec/ponytail.js';

/** Generate AI Rules files (CLAUDE.md, .cursorrules, AGENTS.md) */
export function generateRulesFiles(
  projectRoot: string,
  config: MumuSpecConfig,
  specContext?: SpecContext,
): string[] {
  const generated: string[] = [];

  for (const rulesFile of config.ai.rules_files) {
    const content = generateRulesContent(rulesFile, config, specContext);
    const filePath = join(projectRoot, rulesFile);
    writeText(filePath, content);
    generated.push(filePath);
  }

  return generated;
}

/** Generate rules content for a specific file */
function generateRulesContent(
  fileName: string,
  config: MumuSpecConfig,
  specContext?: SpecContext,
): string {
  const lines: string[] = [];

  const isClaude = fileName === 'CLAUDE.md';
  const isCursor = fileName === '.cursorrules';
  const isAgents = fileName === 'AGENTS.md';

  // Header
  if (isClaude) {
    lines.push('# Claude Code Rules');
  } else if (isCursor) {
    lines.push('# Cursor Rules');
  } else {
    lines.push('# Agent Rules');
  }
  lines.push('');
  lines.push('> Auto-generated by MumuSpec. Do not edit manually.');
  lines.push(`> Project: ${config.project.name} | Language: ${config.project.language}`);
  lines.push('');

  // Project overview
  lines.push('## Project Overview');
  lines.push(`- **Name**: ${config.project.name}`);
  lines.push(`- **Language**: ${config.project.language}`);
  if (config.project.framework) {
    lines.push(`- **Framework**: ${config.project.framework}`);
  }
  lines.push('');

  // Workflow rules
  lines.push('## Workflow Rules');
  lines.push('1. **Worktree Isolation**: Changes are isolated in worktrees by default');
  lines.push('2. **Single Active Change**: Only one active change at a time');
  lines.push('3. **Top-Down Design, Bottom-Up Implementation**: Design from root to leaves, implement from leaves to root');
  lines.push('4. **Red-Green TDD**: Test cases are design output, locked after Design phase');
  lines.push('');

  // Spec context (if provided)
  if (specContext && specContext.layers.length > 0) {
    lines.push('## Specification Context (Progressive Disclosure)');
    lines.push('');
    for (const layer of specContext.layers) {
      if (layer.spec) {
        lines.push(`### Level ${layer.level}: ${layer.scope}`);
        lines.push(`Path: \`${layer.path}\``);
        lines.push('');

        for (const req of layer.spec.requirements) {
          lines.push(`#### ${req.name}`);
          if (req.shall.length > 0) {
            lines.push('**SHALL:**');
            for (const s of req.shall) {
              lines.push(`- ${s}`);
            }
          }
          if (req.shallNot.length > 0) {
            lines.push('**SHALL NOT:**');
            for (const s of req.shallNot) {
              lines.push(`- ${s}`);
            }
          }
          lines.push('');
        }
      }
    }
  }

  // Prohibitions summary
  if (specContext && specContext.prohibitions.length > 0) {
    lines.push('## Prohibitions Summary');
    for (const p of specContext.prohibitions) {
      lines.push(`- ${p}`);
    }
    lines.push('');
  }

  // Ponytail constraints
  if (config.ponytail.enabled) {
    lines.push('## Ponytail Coding Constraints');
    lines.push('');
    lines.push('### 7-Level Priority Ladder');
    lines.push('');
    lines.push('| Level | Question | Action | Type |');
    lines.push('|-------|----------|--------|------|');
    for (const rung of PONYTAIL_LADDER) {
      lines.push(`| ${rung.level} | ${rung.question} | ${rung.action} | ${rung.type} |`);
    }
    lines.push('');

    lines.push('### Hard Constraints');
    lines.push('');
    lines.push('**SHALL NOT:**');
    lines.push('- 禁止引入未被请求的抽象层（YAGNI）');
    lines.push('- 禁止在标准库/平台特性已满足需求时引入新依赖');
    lines.push('- 禁止生成未被请求的样板代码（boilerplate）');
    lines.push('- 禁止用复杂方案替代简单方案（boring over clever）');
    lines.push('');
    lines.push('**SHALL:**');
    lines.push('- 编写新代码前必须检查代码库中是否已有可复用的实现');
    lines.push('- 新代码必须是最小可工作实现（仅写必要的代码）');
    lines.push('- 有意简化必须用 `ponytail:` 注释标记原因');
    lines.push('');

    lines.push('### Non-Lazy Domains (must be rigorous, not lazy)');
    for (const domain of NON_LAZY_DOMAINS) {
      lines.push(`- ${domain}`);
    }
    lines.push('');

    lines.push('### ponytail: Comment Marker');
    lines.push('```typescript');
    lines.push('// ponytail: <reason for intentional simplification>');
    lines.push('```');
    lines.push('');
  }

  // Priority system
  lines.push('## Priority System');
  lines.push('1. User explicit instructions (highest)');
  lines.push('2. MumuSpec SHALL NOT (hard prohibition, cannot be overridden)');
  lines.push('3. MumuSpec SHALL (hard requirement, cannot be skipped)');
  lines.push('4. External Skill guidance (HOW, within constraints)');
  lines.push('5. Default system behavior (lowest)');
  lines.push('');

  // Knowledge layer
  if (config.knowledge.enabled) {
    lines.push('## Knowledge Layer');
    lines.push('- **Code Graph (HOW)**: Use `mumuspec search` / `mumuspec trace` to query code structure');
    lines.push('- **LLM-Wiki (WHY)**: Load knowledge from `.mumuspec/knowledge/` using `mumuspec knowledge context <path>`');
    lines.push('- **PageIndex (WHERE)**: Progressive knowledge loading by scope and freshness');
    lines.push('');
  }

  // CLI commands reference
  lines.push('## Key CLI Commands');
  lines.push('```bash');
  lines.push('mumuspec init [path]                    # Initialize MumuSpec');
  lines.push('mumuspec context <path>                 # Get spec context (progressive disclosure)');
  lines.push('mumuspec validate                       # Validate all spec formats');
  lines.push('mumuspec check                          # Full compliance check');
  lines.push('mumuspec new <name>                     # Create new change');
  lines.push('mumuspec status [name]                  # View change status');
  lines.push('mumuspec list                           # List active changes');
  lines.push('mumuspec archive <name>                 # Archive change');
  lines.push('mumuspec discard <name>                 # Discard change');
  lines.push('mumuspec drift                          # Drift detection');
  lines.push('mumuspec guard <change> <phase>         # Phase guard check');
  lines.push('mumuspec doctor                         # Environment diagnostics');
  lines.push('```');
  lines.push('');

  // MCP Server
  if (config.ai.mcp_server) {
    lines.push('## MCP Server');
    lines.push('MumuSpec MCP Server provides standardized AI tool interface:');
    lines.push('```json');
    lines.push('{');
    lines.push('  "mcpServers": {');
    lines.push('    "mumuspec": {');
    lines.push('      "command": "npx",');
    lines.push('      "args": ["@mumuspec/mcp-server"],');
    lines.push('      "env": { "MUMUSPEC_ROOT": "${workspaceRoot}" }');
    lines.push('    }');
    lines.push('  }');
    lines.push('}');
    lines.push('```');
    lines.push('');
  }

  return lines.join('\n');
}
