/**
 * HTML Reporter — Auto-Evaluate Engine (R-0002)
 *
 * Generate HTML reports visualizing loop evaluation metrics over rounds.
 * Uses inline SVG for charts (no external dependencies).
 */

import { writeFileSync } from 'node:fs';
import type { MetricsSnapshot } from './types.js';

/**
 * Generate an HTML report from metrics history.
 */
export function generateHtmlReport(
  changeName: string,
  history: MetricsSnapshot[],
  outputPath: string,
): void {
  const html = buildHtml(changeName, history);
  writeFileSync(outputPath, html, 'utf-8');
}

/**
 * Build the complete HTML document.
 */
function buildHtml(changeName: string, history: MetricsSnapshot[]): string {
  const rounds = history.map(h => h.round);
  const progressData = history.map(h => h.progress);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Loop Report — ${escapeHtml(changeName)}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 2rem; background: #f5f5f5; }
    .container { max-width: 900px; margin: 0 auto; background: white; padding: 2rem; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); }
    h1 { color: #1a1a1a; margin-bottom: 0.5rem; }
    .subtitle { color: #666; margin-bottom: 2rem; }
    .chart { margin: 2rem 0; }
    .metrics-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin: 1.5rem 0; }
    .metric-card { background: #f8f9fa; padding: 1rem; border-radius: 6px; border-left: 4px solid #4a90d9; }
    .metric-name { font-size: 0.85rem; color: #666; }
    .metric-value { font-size: 1.5rem; font-weight: bold; color: #1a1a1a; }
    .footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #eee; color: #999; font-size: 0.85rem; }
    .status-converged { color: #27ae60; }
    .status-exhausted { color: #e74c3c; }
    .status-active { color: #f39c12; }
  </style>
</head>
<body>
  <div class="container">
    <h1>Loop Evaluation Report</h1>
    <div class="subtitle">Change: <strong>${escapeHtml(changeName)}</strong> &mdash; ${history.length} round(s)</div>

    <h2>Progress Trend</h2>
    <div class="chart">
      ${generateSvgChart(rounds, progressData)}
    </div>

    <h2>Per-Round Metrics</h2>
    <div class="metrics-grid">
      ${history.map(generateMetricCard).join('\n      ')}
    </div>

    <div class="footer">
      Generated by MumuSpec Loop Auto-Evaluate Engine (R-0002)
    </div>
  </div>
</body>
</html>`;
}

/**
 * Generate an SVG line chart for progress data.
 */
function generateSvgChart(rounds: number[], values: number[]): string {
  if (values.length === 0) {
    return '<p>No data available</p>';
  }

  const width = 800;
  const height = 200;
  const padding = 40;
  const chartW = width - padding * 2;
  const chartH = height - padding * 2;

  // Calculate point positions
  const points: Array<{ x: number; y: number }> = [];
  for (let i = 0; i < values.length; i++) {
    const x = padding + (i / Math.max(1, values.length - 1)) * chartW;
    const y = padding + (1 - values[i]) * chartH;
    points.push({ x, y });
  }

  // Build polyline
  const polyline = points.map(p => `${p.x},${p.y}`).join(' ');

  // Threshold line at 0.85
  const thresholdY = padding + (1 - 0.85) * chartH;

  return `<svg viewBox="0 0 ${width} ${height}" style="width:100%;height:auto;background:#fafafa;border-radius:4px;">
    <!-- Y axis labels -->
    <text x="5" y="${padding + 4}" font-size="10" fill="#999">100%</text>
    <text x="5" y="${padding + chartH / 2 + 4}" font-size="10" fill="#999">50%</text>
    <text x="5" y="${padding + chartH + 4}" font-size="10" fill="#999">0%</text>
    <!-- Threshold line (85%) -->
    <line x1="${padding}" y1="${thresholdY}" x2="${width - padding}" y2="${thresholdY}" stroke="#e74c3c" stroke-dasharray="4,4" opacity="0.6"/>
    <text x="${width - padding + 5}" y="${thresholdY + 4}" font-size="9" fill="#e74c3c">85%</text>
    <!-- Axes -->
    <line x1="${padding}" y1="${padding}" x2="${padding}" y2="${padding + chartH}" stroke="#ccc"/>
    <line x1="${padding}" y1="${padding + chartH}" x2="${width - padding}" y2="${padding + chartH}" stroke="#ccc"/>
    <!-- Data line -->
    <polyline points="${polyline}" fill="none" stroke="#4a90d9" stroke-width="2"/>
    <!-- Data points -->
    ${points.map((p, i) => `<circle cx="${p.x}" cy="${p.y}" r="4" fill="#4a90d9"/>
    <text x="${p.x}" y="${p.y - 10}" text-anchor="middle" font-size="9" fill="#333">R${rounds[i]}: ${Math.round(values[i] * 100)}%</text>`).join('\n    ')}
  </svg>`;
}

/**
 * Generate a metrics card for a single round.
 */
function generateMetricCard(snapshot: MetricsSnapshot): string {
  const statusClass = snapshot.goalAchieved ? 'status-converged' : 'status-active';
  const statusText = snapshot.goalAchieved ? '✓ Converged' : 'Active';

  const metricsList = snapshot.metrics.map(m =>
    `<div style="font-size:0.8rem;color:#555;">${escapeHtml(m.name)}: ${Math.round(m.value * 100)}%</div>`
  ).join('');

  return `<div class="metric-card">
    <div class="metric-name">Round ${snapshot.round}</div>
    <div class="metric-value ${statusClass}">${Math.round(snapshot.progress * 100)}%</div>
    <div style="font-size:0.8rem;color:#666;">${statusText}</div>
    ${metricsList}
  </div>`;
}

/**
 * Escape HTML special characters.
 */
function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
