/**
 * Meta-Evolution type definitions (R-0005).
 *
 * Defines data models for:
 * - Effectiveness scoring of constraint/skill/knowledge entries
 * - Evolution reports and recommendations
 * - Knowledge layer freshness evolution actions
 * - Skill recommendation based on scope
 */

// ════════════════════════════════════════════════════════════════════
// Effectiveness Scoring
// ════════════════════════════════════════════════════════════════════

/** Effectiveness score for a single constraint entry. */
export interface EffectivenessScore {
  /** Constraint id, e.g. "E-GUARD-003" */
  constraintId: string;
  /** Pass rate [0, 1] — passes / total checks */
  passRate: number;
  /** False positive rate [0, 1] — false positives / failures */
  falsePositiveRate: number;
  /** Composite score = passRate × (1 - falsePositiveRate × penaltyWeight) */
  score: number;
  /** ISO 8601 timestamp of last evaluation */
  lastEvaluated: string;
  /** Sample size used for calculation (affects confidence) */
  sampleSize: number;
  /** Whether this score is statistically reliable (sampleSize >= 5) */
  reliable: boolean;
}

/** Report generated by `--analyze`. */
export interface EvolutionReport {
  generatedAt: string;
  scores: EffectivenessScore[];
  /** Constraint ids with score < threshold (default 0.3) */
  lowPerformingIds: string[];
  /** Human-readable recommendations */
  recommendations: string[];
  /** Total constraints evaluated */
  totalEvaluated: number;
}

/** Configuration for the scoring engine. */
export interface ScoringConfig {
  /** Threshold below which a constraint is considered under-performing */
  lowScoreThreshold: number;
  /** Penalty weight for false positives (default 1.5) */
  penaltyWeight: number;
  /** Minimum sample size for reliable score */
  minSampleSize: number;
  /** Sliding window size for statistics (default 20) */
  windowSize: number;
}

export const DEFAULT_SCORING_CONFIG: ScoringConfig = {
  lowScoreThreshold: 0.3,
  penaltyWeight: 1.5,
  minSampleSize: 5,
  windowSize: 20,
};

// ════════════════════════════════════════════════════════════════════
// Statistics Persistence
// ════════════════════════════════════════════════════════════════════

/** A single check result recorded for future scoring. */
export interface CheckRecord {
  /** ISO 8601 timestamp */
  timestamp: string;
  /** Constraint id */
  constraintId: string;
  /** Whether this check passed */
  passed: boolean;
  /** Whether this was a false positive (manual override marked) */
  falsePositive: boolean;
}

// ════════════════════════════════════════════════════════════════════
// Knowledge Layer Evolution (R0)
// ════════════════════════════════════════════════════════════════════

/** Action to take on a knowledge page. */
export type KnowledgeAction = 'promote_freshness' | 'demote_freshness' | 'refresh_page_index';

/** Result of a knowledge evolution analysis. */
export interface KnowledgeEvolutionAction {
  pageId: string;
  action: KnowledgeAction;
  reason: string;
  previousValue: string;
  newValue: string;
}

// ════════════════════════════════════════════════════════════════════
// Skill Recommendation (R1)
// ════════════════════════════════════════════════════════════════════

/** A skill recommendation based on scope/context. */
export interface SkillRecommendation {
  skillId: string;
  skillName: string;
  relevanceScore: number;
  reason: string;
}

/** Result of skill recommendation. */
export interface SkillRecommendResult {
  recommendations: SkillRecommendation[];
  /** Accuracy threshold (0.6 = 60%) */
  confidenceThreshold: number;
}
