/**
 * Rules generator — canonical-first AGENTS.md + bridge files (goal-p0-dispatch-gate, C2/D1).
 *
 * Pure function, NO IO: input is the rule target declaration (AGENT_RULE_TARGETS)
 * plus the spec context; output is a plan of `{ path, content?, action }` items.
 * The caller (installer-ops / rules/generator.ts) executes the plan on disk.
 * This split keeps the three-state conflict policy (absent→create /
 * managed→update / user→skip+warn, `--force-rules` takes over) unit-testable
 * without touching the filesystem.
 *
 * Single source of truth for BOTH rendering and three-state decisions:
 * src/rules/generator.ts (mumuspec rules generate / init) consumes
 * decideAction + render* from here — two code paths, one content contract.
 *
 * D2: legacy targets (.cursorrules / .windsurfrules) are intentionally absent —
 * the generator never produces them.
 */
import type { AgentType } from './installer-registry.js';
import { AGENT_RULE_TARGETS } from './installer-registry.js';
import type { MumuSpecConfig } from '../core/config.js';
import type { SpecContext } from '../core/types.js';
import { PONYTAIL_LADDER } from '../spec/ponytail.js';

/** Marker that identifies MumuSpec-managed files (三态判定的托管凭证) */
export const MANAGED_MARKER = 'Auto-generated by MumuSpec. Do not edit manually.';

/** Spec context supplied by the caller (read from the project's spec chain) */
export interface RuleGenContext {
  /** 规范链摘要（specs 摘要 / 项目约束链） */
  specSummary: string;
  /** Ponytail 编码约束（SHALL/SHALL NOT 速览） */
  ponytail: string;
  /** CLI 速查 */
  cliCommands: string;
  /** MCP 入口指引 */
  mcpEntry: string;
}

export interface RuleFilePlan {
  path: string;
  /** undefined when action === 'skip' — skip 计划绝不携带落盘内容（TC-A3） */
  content?: string;
  action: 'create' | 'update' | 'skip';
  /** skip/force 诊断信息 */
  diagnostic?: string;
}

export interface RenderRuleFilesOptions {
  /** In-memory snapshot of existing files (path → content; undefined = absent) */
  existingFiles?: Record<string, string | undefined>;
  /** `--force-rules`: take over user-owned files (D1) */
  forceRules?: boolean;
}

/** Render the canonical AGENTS.md content (marker header + 4 contract sections) */
export function renderCanonicalRules(ctx: RuleGenContext): string {
  return [
    `> ${MANAGED_MARKER}`,
    '> Regenerate: mumuspec init — or mumuspec install --agent <agent>',
    '',
    '# AGENTS.md',
    '',
    '## 规范链摘要',
    '',
    ctx.specSummary,
    '',
    '## Ponytail 编码约束',
    '',
    ctx.ponytail,
    '',
    '## CLI 速查',
    '',
    ctx.cliCommands,
    '',
    '## MCP 入口',
    '',
    ctx.mcpEntry,
    '',
  ].join('\n');
}

/** Render a thin-shell bridge file — first line is the include directive */
export function renderBridgeFile(includeLine: string): string {
  return [
    includeLine,
    '',
    `> ${MANAGED_MARKER} — 本文件是 AGENTS.md 的薄壳桥接；请编辑 AGENTS.md 或运行 mumuspec init 重新生成。`,
    '',
  ].join('\n');
}

/** Three-state conflict decision for one file (D1 标记分路) */
export function decideAction(
  _path: string,
  current: string | undefined | null,
  forceRules: boolean,
): { action: 'create' | 'update' | 'skip'; diagnostic?: string } {
  if (current === undefined || current === null) return { action: 'create' };
  if (current.includes(MANAGED_MARKER)) return { action: 'update' };
  if (forceRules) return { action: 'update', diagnostic: 'force-rules: 已接管用户手写文件' };
  return { action: 'skip', diagnostic: 'user-owned file — skipped（--force-rules 可接管）' };
}

/** Three-state conflict decision for one file (D1 标记分路) */
function planFor(
  path: string,
  managedContent: string,
  existing: Record<string, string | undefined>,
  forceRules: boolean,
): RuleFilePlan {
  const { action, diagnostic } = decideAction(path, existing[path], forceRules);
  if (action === 'skip') return { path, action, diagnostic };
  return { path, content: managedContent, action, diagnostic };
}

/**
 * Render the rule-file plan for one agent.
 *
 * Table-driven: plans come from AGENT_RULE_TARGETS[agent]; agents without a
 * rule target (catpaw/cursor/trae/workbuddy/opencode) return an empty plan —
 * their distribution keeps existing behavior. Adding an agent = adding a
 * table entry, never touching this function (TC-A5).
 */
export function renderRuleFiles(
  agent: AgentType,
  ctx: RuleGenContext,
  options: RenderRuleFilesOptions = {},
): RuleFilePlan[] {
  const target = AGENT_RULE_TARGETS[agent];
  if (!target) return [];

  const existing = options.existingFiles ?? {};
  const forceRules = options.forceRules === true;
  const canonical = renderCanonicalRules(ctx);

  const plans: RuleFilePlan[] = [planFor(target.rulesFile, canonical, existing, forceRules)];
  for (const bridge of Object.values(target.bridges)) {
    plans.push(planFor(bridge.file, renderBridgeFile(bridge.line), existing, forceRules));
  }
  return plans;
}

// ── Context construction（config/specContext → 四节文本） ──────────

const DEFAULT_CLI_COMMANDS = [
  'mumuspec init [path]                # Initialize MumuSpec',
  'mumuspec context <path>             # Get spec context (progressive disclosure)',
  'mumuspec new <name>                 # Create new change',
  'mumuspec status [name]              # View change status',
  'mumuspec guard <change> <phase>     # Phase guard check',
  'mumuspec validate / check / drift   # Validate / compliance / drift',
  'mumuspec archive <name> --confirm   # Archive change',
  'mumuspec doctor                     # Environment diagnostics',
].join('\n');

const DEFAULT_MCP_ENTRY = [
  'MumuSpec MCP Server provides standardized AI tool interface:',
  '```json',
  '{',
  '  "mcpServers": {',
  '    "mumuspec": { "command": "npx", "args": ["@mumuspec/mcp-server"],',
  '      "env": { "MUMUSPEC_ROOT": "${workspaceRoot}" } }',
  '  }',
  '}',
  '```',
].join('\n');

/**
 * Build the four-section RuleGenContext from project config + spec context.
 * Both arguments optional — install-time callers may run before `mumuspec init`
 * exists, in which case static default content is used.
 */
export function buildRuleGenContext(
  config?: MumuSpecConfig,
  specContext?: SpecContext,
): RuleGenContext {
  const overview: string[] = [];
  if (config?.project?.name) {
    overview.push(`- **Project**: ${config.project.name} (${config.project.language}${config.project.framework ? `, ${config.project.framework}` : ''})`);
  }

  const specLines: string[] = [];
  if (specContext && specContext.layers.length > 0) {
    for (const layer of specContext.layers) {
      if (!layer.spec) continue;
      specLines.push(`### ${layer.scope} (\`${layer.path}\`)`);
      for (const req of layer.spec.requirements) {
        specLines.push(`- ${req.name}`);
        for (const s of req.shall) specLines.push(`  - SHALL: ${s}`);
        for (const s of req.shallNot) specLines.push(`  - SHALL NOT: ${s}`);
      }
      specLines.push('');
    }
  }
  if (specContext?.prohibitions?.length) {
    specLines.push('**Prohibitions:**');
    for (const p of specContext.prohibitions) specLines.push(`- ${p}`);
    specLines.push('');
  }
  if (specLines.length === 0) {
    specLines.push('（规范链尚未生成——运行 `mumuspec init` / `mumuspec context <path>` 加载渐进式规范链。）');
  }

  const ponytailLines = [
    '| Level | Question | Action | Type |',
    '|-------|----------|--------|------|',
    ...PONYTAIL_LADDER.map((r) => `| ${r.level} | ${r.question} | ${r.action} | ${r.type} |`),
    '',
    'SHALL NOT: 无未被请求的抽象（YAGNI）/ 标准库已满足时不引新依赖 / 无样板代码 / boring over clever',
    'SHALL: 先查可复用实现 / 最小可工作实现 / 有意简化用 `ponytail:` 注释标记',
  ];

  return {
    specSummary: [...overview, ...specLines].join('\n').trim(),
    ponytail: ponytailLines.join('\n'),
    cliCommands: DEFAULT_CLI_COMMANDS,
    mcpEntry: DEFAULT_MCP_ENTRY,
  };
}
