import { existsSync, readFileSync, writeFileSync, chmodSync, mkdirSync, unlinkSync } from 'node:fs';
import { join, resolve, parse } from 'node:path';
import { checkCompliance, detectDrift } from '../guard/checker.js';
import { findProjectRoot } from '../core/utils.js';
import { loadConfig } from '../core/config.js';
import { readReverseIndex } from '../knowledge/manager.js';
import type { GuardResult, DriftResult } from '../core/types.js';

export type HookType = 'pre-commit' | 'post-commit' | 'post-merge' | 'post-checkout' | 'commit-msg';

export interface HookInstallResult {
  success: boolean;
  hook: string;
  path?: string;
  error?: string;
  skipped?: boolean;
}

export interface HookRunResult {
  hook: string;
  passed: boolean;
  errors: string[];
  warnings: string[];
}

export interface HookStatus {
  installed: HookType[];
  available: HookType[];
}

const HOOK_SCRIPT_VERSION = '0.12.2';

const HOOKS: HookType[] = ['pre-commit', 'post-commit', 'post-merge', 'post-checkout', 'commit-msg'];

// Shell script template — ponytail: minimal shell, just delegates to node CLI
const HOOK_TEMPLATE = `#!/bin/sh
# MumuSpec git hook (auto-generated by \`mumuspec hooks install\`)
# Version: ${HOOK_SCRIPT_VERSION}
# Hook: {{HOOK_TYPE}}
# DO NOT EDIT MANUALLY — run \`mumuspec hooks install\` to regenerate

mumuspec hooks run {{HOOK_TYPE}} "$@" 2>&1
exit $?
`;

const HOOK_TEMPLATE_WIN = `@echo off
REM MumuSpec git hook (auto-generated by \`mumuspec hooks install\`)
REM Version: ${HOOK_SCRIPT_VERSION}
REM Hook: {{HOOK_TYPE}}
REM DO NOT EDIT MANUALLY — run \`mumuspec hooks install\` to regenerate

mumuspec hooks run {{HOOK_TYPE}} %*
exit /b %ERRORLEVEL%
`;

function findGitRoot(startDir: string = process.cwd()): string | null {
  let dir = resolve(startDir);
  const { root } = parse(dir);

  while (dir !== root) {
    if (existsSync(join(dir, '.git'))) return dir;
    dir = resolve(dir, '..');
  }
  if (existsSync(join(root, '.git'))) return root;
  return null;
}

function installSingleHook(
  gitRoot: string,
  hookType: HookType,
  force: boolean = false,
): HookInstallResult {
  const hooksDir = join(gitRoot, '.git', 'hooks');

  if (!existsSync(hooksDir)) {
    try {
      mkdirSync(hooksDir, { recursive: true });
    } catch (err) {
      return {
        success: false,
        hook: hookType,
        error: `Failed to create hooks directory: ${err instanceof Error ? err.message : String(err)}`,
      };
    }
  }

  const isWindows = process.platform === 'win32';
  const hookPath = join(hooksDir, hookType);

  if (existsSync(hookPath)) {
    try {
      const content = readFileSync(hookPath, 'utf8');
      if (!content.includes('MumuSpec git hook') && !force) {
        const backupPath = `${hookPath}.mumuspec-backup`;
        writeFileSync(backupPath, content);
        return {
          success: false,
          hook: hookType,
          path: hookPath,
          error: `Existing non-mumuspec hook backed up to ${backupPath}. Use --force to overwrite.`,
          skipped: true,
        };
      }
    } catch {
      // proceed
    }
  }

  const template = isWindows ? HOOK_TEMPLATE_WIN : HOOK_TEMPLATE;
  const script = template.replace(/{{HOOK_TYPE}}/g, hookType);

  try {
    writeFileSync(hookPath, script, { mode: 0o755 });
    if (!isWindows) {
      try { chmodSync(hookPath, 0o755); } catch { /* ignore */ }
    }
    return { success: true, hook: hookType, path: hookPath };
  } catch (err) {
    return {
      success: false,
      hook: hookType,
      path: hookPath,
      error: `Failed to write hook: ${err instanceof Error ? err.message : String(err)}`,
    };
  }
}

/**
 * Install all mumuspec git hooks.
 */
export function installHooks(
  options: {
    workspacePath?: string;
    force?: boolean;
    hooks?: HookType[];
  } = {},
): HookInstallResult[] {
  const workspacePath = options.workspacePath || process.cwd();
  const gitRoot = findGitRoot(workspacePath);

  if (!gitRoot) {
    return [
      {
        success: false,
        hook: 'pre-commit',
        error: 'No .git directory found. Ensure the project is a git repository.',
      },
    ];
  }

  const hooksToInstall = options.hooks || HOOKS;
  return hooksToInstall.map((hookType) => installSingleHook(gitRoot, hookType, options.force));
}

/**
 * Get status of hook installation.
 */
export function getHookStatus(workspacePath?: string): HookStatus {
  const wsPath = workspacePath || process.cwd();
  const gitRoot = findGitRoot(wsPath);

  if (!gitRoot) {
    return { installed: [], available: HOOKS };
  }

  const hooksDir = join(gitRoot, '.git', 'hooks');
  const installed: HookType[] = [];

  for (const hookType of HOOKS) {
    const hookPath = join(hooksDir, hookType);
    if (existsSync(hookPath)) {
      try {
        const content = readFileSync(hookPath, 'utf8');
        if (content.includes('MumuSpec git hook')) {
          installed.push(hookType);
        }
      } catch { /* ignore */ }
    }
  }

  return { installed, available: HOOKS };
}

/**
 * Uninstall mumuspec hooks.
 */
export function uninstallHooks(workspacePath?: string): HookInstallResult[] {
  const wsPath = workspacePath || process.cwd();
  const gitRoot = findGitRoot(wsPath);

  if (!gitRoot) {
    return [
      {
        success: false,
        hook: 'pre-commit',
        error: 'No .git directory found.',
      },
    ];
  }

  const hooksDir = join(gitRoot, '.git', 'hooks');
  const results: HookInstallResult[] = [];

  for (const hookType of HOOKS) {
    const hookPath = join(hooksDir, hookType);

    if (!existsSync(hookPath)) {
      results.push({ success: true, hook: hookType, skipped: true });
      continue;
    }

    try {
      const content = readFileSync(hookPath, 'utf8');
      if (!content.includes('MumuSpec git hook')) {
        results.push({
          success: false,
          hook: hookType,
          error: 'Not a mumuspec hook (skipped)',
          skipped: true,
        });
        continue;
      }

      unlinkSync(hookPath);
      results.push({ success: true, hook: hookType });
    } catch (err) {
      results.push({
        success: false,
        hook: hookType,
        error: `Failed to remove: ${err instanceof Error ? err.message : String(err)}`,
      });
    }
  }

  return results;
}

/**
 * Run guard logic for a specific hook type.
 */
export function runHook(
  hookType: HookType,
  args: string[] = [],
  workspacePath?: string,
): HookRunResult {
  const wsPath = workspacePath || process.cwd();
  const projectRoot = findProjectRoot(wsPath) || wsPath;

  const errors: string[] = [];
  const warnings: string[] = [];

  switch (hookType) {
    case 'pre-commit':
      runPreCommit(projectRoot, errors, warnings);
      break;
    case 'post-commit':
      runPostCommit(projectRoot, errors, warnings);
      break;
    case 'post-merge':
      runPostMerge(projectRoot, errors, warnings);
      break;
    case 'post-checkout':
      runPostCheckout(projectRoot, errors, warnings);
      break;
    case 'commit-msg':
      runCommitMsg(projectRoot, args, errors, warnings);
      break;
    default:
      warnings.push(`Unknown hook type: ${hookType}`);
  }

  return {
    hook: hookType,
    passed: errors.length === 0,
    errors,
    warnings,
  };
}

function runPreCommit(projectRoot: string, errors: string[], warnings: string[]): void {
  const result: GuardResult = checkCompliance(projectRoot, { shallNot: true });

  for (const error of result.errors) {
    errors.push(`[${error.code}] ${error.message}${error.detail ? ` (${error.detail})` : ''}`);
  }
  for (const warn of result.warnings) {
    warnings.push(`[${warn.code}] ${warn.message}`);
  }

  const driftResults: DriftResult[] = detectDrift(projectRoot);
  for (const drift of driftResults) {
    if (drift.severity === 'ERROR') {
      errors.push(`[DRIFT] ${drift.message} (${drift.type})`);
    } else if (drift.severity === 'WARN') {
      warnings.push(`[DRIFT] ${drift.message} (${drift.type})`);
    }
  }
}

function runPostMerge(projectRoot: string, errors: string[], warnings: string[]): void {
  const driftResults: DriftResult[] = detectDrift(projectRoot);
  for (const drift of driftResults) {
    if (drift.severity === 'ERROR') {
      errors.push(`[DRIFT] ${drift.message} (${drift.type})`);
    } else {
      warnings.push(`[DRIFT] ${drift.message} (${drift.type})`);
    }
  }
}

function runPostCheckout(projectRoot: string, _errors: string[], warnings: string[]): void {
  const mumuDir = join(projectRoot, '.mumuspec');
  if (!existsSync(mumuDir)) {
    warnings.push('.mumuspec directory not found — project may not be initialized');
  }
}

function runCommitMsg(
  projectRoot: string,
  args: string[],
  errors: string[],
  warnings: string[],
): void {
  if (args.length === 0) return;

  const msgFilePath = args[0];
  if (!existsSync(msgFilePath)) return;

  const content = readFileSync(msgFilePath, 'utf8').trim();
  if (content.length < 10) {
    errors.push('Commit message too short (minimum 10 characters)');
  }
  if (content.length > 200) {
    errors.push('Commit message too long (maximum 200 characters for subject line)');
  }

  // Parse Knowledge-Impact block (UA-style)
  const ki = parseKnowledgeImpact(content);
  if (ki) {
    // Block SUPERSEDES without a formal change
    if (ki.supersedes.length > 0) {
      errors.push(
        `Knowledge-Impact SUPERSEDES detected (${ki.supersedes.join(', ')}). ` +
        `Please create a formal change to supersede knowledge pages.`
      );
    }
    // Save context for post-commit hook
    if (ki.implements.length > 0 || ki.affects.length > 0) {
      try {
        const ctxPath = join(projectRoot, '.mumuspec', 'knowledge', '.commit-context.json');
        mkdirSync(join(projectRoot, '.mumuspec', 'knowledge'), { recursive: true });
        writeFileSync(ctxPath, JSON.stringify(ki, null, 2));
      } catch { /* ignore write failures */ }
    }
    if (ki.affects.length > 0) {
      warnings.push(`Knowledge-Impact: ${ki.affects.length} page(s) may be affected`);
    }
  }
}

// ========== Understand-A Style Hooks (0.13.0+) ==========

/** Parsed Knowledge-Impact block from commit message */
export interface KnowledgeImpact {
  implements: string[];
  affects: string[];
  supersedes: string[];
}

/**
 * Parse Knowledge-Impact block from commit message (UA-style)
 * Format:
 *   Knowledge-Impact:
 *     IMPLEMENTS: [KP-xxx, ...]
 *     AFFECTS: [KP-xxx, ...]
 *     SUPERSEDES: [KP-xxx, ...]
 */
export function parseKnowledgeImpact(message: string): KnowledgeImpact | null {
  const impactMatch = message.match(/Knowledge-Impact:\s*\n([\s\S]*?)(?:\n\n|\n[A-Z]|$)/i);
  if (!impactMatch) return null;

  const block = impactMatch[1];
  const result: KnowledgeImpact = {
    implements: [],
    affects: [],
    supersedes: [],
  };

  const impMatch = block.match(/IMPLEMENTS:\s*\[([^\]]*)\]/i);
  if (impMatch) result.implements = impMatch[1].split(',').map((s) => s.trim()).filter(Boolean);

  const affMatch = block.match(/AFFECTS:\s*\[([^\]]*)\]/i);
  if (affMatch) result.affects = affMatch[1].split(',').map((s) => s.trim()).filter(Boolean);

  const supMatch = block.match(/SUPERSEDES:\s*\[([^\]]*)\]/i);
  if (supMatch) result.supersedes = supMatch[1].split(',').map((s) => s.trim()).filter(Boolean);

  return result;
}

/**
 * Post-commit hook: incremental knowledge update (UA-style)
 * Refreshes verified_at for Knowledge Pages affected by the commit.
 */
function runPostCommit(projectRoot: string, _errors: string[], warnings: string[]): void {
  const config = loadConfig(projectRoot);
  if (!config.knowledge.commit_update.enabled) return;

  try {
    // Read commit context (written by commit-msg hook)
    const ctxPath = join(projectRoot, '.mumuspec', 'knowledge', '.commit-context.json');
    let context: KnowledgeImpact | null = null;
    if (existsSync(ctxPath)) {
      try {
        context = JSON.parse(readFileSync(ctxPath, 'utf8')) as KnowledgeImpact;
        // Clean up after read
        unlinkSync(ctxPath);
      } catch { /* ignore */ }
    }

    // Read reverse index to find affected pages
    const reverseIndex = readReverseIndex(projectRoot, config);
    const affectedPageIds = new Set<string>();

    if (context) {
      for (const id of [...context.implements, ...context.affects]) {
        affectedPageIds.add(id);
      }
    } else {
      // No context — refresh all (conservative fallback)
      for (const entry of reverseIndex) {
        for (const pageId of entry.knowledge_pages) {
          affectedPageIds.add(pageId);
        }
      }
    }

    if (affectedPageIds.size > 0 && warnings.length === 0) {
      warnings.push(`${affectedPageIds.size} knowledge page(s) queued for freshness update`);
    }
  } catch { /* fail silently — hook must not block git */}
}
